import Main from '../components/Main'
import Head from 'next/head'
import { GraphQLClient, gql } from 'graphql-request'
import ImageCard from '../components/ImageCard'
import Link from 'next/link'

const graphcms = new GraphQLClient("https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/cl9r7n6ix1sqc01te94n45g0d/master")

const QUERY = gql`
{
  attractions {
    id,
    title,
    slug
    description,
    coverPhoto {
      url,
    }
  }
}
`

export async function getStaticProps() {
  const {attractions} = await graphcms.request(QUERY)
  return {
    props: {
      attractions,
    },
  }
}


export default function Home({attractions}: any) {
  return (  
    <div>
      <Head>
        <title>Danang Travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='hero-container'>

        {/* body text */}
        <Main />

        {/* image row */}
        <div className="flex gap-8">
          {attractions.map(({id, coverPhoto, title, slug}: any) =>  (
            <Link key={id} href={"/places/" + slug}>
              <ImageCard
                coverPhoto={coverPhoto}
                title={title}
              />
            </Link>
          ))}
        </div>     
      </div>
    </div>
  )
}
